import pytest
from fastapi.testclient import TestClient

from app import server
from app.engine import PokerEngine


@pytest.fixture(autouse=True)
def clean_table():
    server.engine = PokerEngine(starting_stack=1000, small_blind=10, big_blind=20)
    server.connections.clear()
    server.spectators.clear()
    server.series_total = None
    server.series_completed = 0
    server.series_active = False


def test_websocket_rejects_actions_from_an_unseated_connection():
    with TestClient(server.app) as client:
        with client.websocket_connect("/ws") as websocket:
            websocket.send_json({"type": "action", "action": "call"})
            assert websocket.receive_json() == {"type": "error", "message": "Join the table first"}


def test_observer_does_not_take_a_poker_seat():
    with TestClient(server.app) as client:
        with client.websocket_connect("/ws") as websocket:
            websocket.send_json({"type": "observe"})
            state = websocket.receive_json()["payload"]
            assert state["players"] == []
            assert server.engine.players == {}


def test_observer_can_start_a_ready_table_without_taking_a_seat():
    with TestClient(server.app) as client:
        with client.websocket_connect("/ws") as instructor, client.websocket_connect("/ws") as bot_one, client.websocket_connect("/ws") as bot_two:
            instructor.send_json({"type": "observe"})
            instructor.receive_json()
            bot_one.send_json({"type": "join", "name": "Bot One", "player_id": "bot-1"})
            bot_one.receive_json()
            bot_two.send_json({"type": "join", "name": "Bot Two", "player_id": "bot-2"})
            bot_two.receive_json()

            instructor.send_json({"type": "start_hand"})
            # The instructor has queued snapshots from both joins. Read until
            # the broadcast generated by start_hand reaches this socket.
            phases = [instructor.receive_json()["payload"]["phase"] for _ in range(3)]
            assert "PREFLOP" in phases
            assert server.engine.phase == "PREFLOP"
            assert len(server.engine.players) == 2


def test_instructor_can_start_the_fixed_ten_hand_series():
    with TestClient(server.app) as client:
        with client.websocket_connect("/ws") as instructor, client.websocket_connect("/ws") as bot_one, client.websocket_connect("/ws") as bot_two:
            instructor.send_json({"type": "observe"})
            instructor.receive_json()
            bot_one.send_json({"type": "join", "name": "Bot One", "player_id": "bot-1"})
            bot_one.receive_json()
            bot_two.send_json({"type": "join", "name": "Bot Two", "player_id": "bot-2"})
            bot_two.receive_json()

            instructor.send_json({"type": "start_series"})
            states = [instructor.receive_json()["payload"] for _ in range(3)]
            assert any(state["phase"] == "PREFLOP" for state in states)
            assert server.series_total == 10
            assert server.series_active is True


def test_join_requires_stable_bot_identity():
    with TestClient(server.app) as client:
        with client.websocket_connect("/ws") as websocket:
            websocket.send_json({"type": "join", "name": "", "player_id": "bot-1"})
            assert websocket.receive_json()["type"] == "error"


def test_start_hand_requires_two_players_with_chips():
    with TestClient(server.app) as client:
        with client.websocket_connect("/ws") as websocket_one, client.websocket_connect("/ws") as websocket_two:
            websocket_one.send_json({"type": "join", "name": "Bot One", "player_id": "bot-1"})
            assert websocket_one.receive_json()["type"] == "state"
            assert server.engine.can_start_hand() is False

            websocket_two.send_json({"type": "join", "name": "Bot Two", "player_id": "bot-2"})
            assert websocket_two.receive_json()["type"] == "state"
            assert server.engine.can_start_hand() is True
